---
argument_specs:
  main:
    short_description: Set a system-wide environment variable.
    options:
      name:
        type: "str"
        required: true
      value:
        type: "str"
        required: true
