---
- hosts: windows
  tasks:
    - name: Check for PowerShell 7
      ansible.windows.win_powershell:
        script: |
          $PSVersionTable.PSVersion.Major
        arguments:
          - -ExecutionPolicy
          - ByPass
      register: pwsh_output
      failed_when:
        - "pwsh_output.output[0] < 5"

- name: Set Scoop & Chocolatey environment variables
  hosts: windows
  tasks:
    - name: Set variables
      include_role:
        name: environment
      vars:
        variableName: "{{ item[0] }}"
        variableValue: "{{ item[1] }}"
      loop:
        - ["SCOOP", "{{ scoop.local }}"]
        - ["SCOOPGLOBAL", "{{ scoop.global }}"]
        - ["ChocolateyInstall", "{{ chocolatey.directory }}"]

- import_playbook: playbooks/scoop.yml
- import_playbook: playbooks/choco.yml
- import_playbook: playbooks/rust.yml
- import_playbook: playbooks/node.yml
- import_playbook: playbooks/npm.yml
- import_playbook: playbooks/python.yml
- import_playbook: playbooks/fonts.yml
