---
- name: Set Scoop & Chocolatey environment variables
  hosts: windows
  tasks:
    - name: Set variables
      include_role:
        name: environment
      vars:
        name: "{{ item[0] }}"
        value: "{{ item[1] }}"
      loop:
        - ["SCOOP", "{{ scoop.local }}"]
        - ["SCOOPGLOBAL", "{{ scoop.global }}"]
        - ["ChocolateyInstall", "{{ chocolatey.directory }}"]

- import_playbook: playbooks/scoop.yml
- import_playbook: playbooks/choco.yml
- import_playbook: playbooks/rust.yml
- import_playbook: playbooks/node.yml
- import_playbook: playbooks/npm.yml
