---
- name: Install fonts
  vars:
    allTheIconsFonts: "{{ lookup('file', '../files/all-the-icons.json') | from_json }}"
    iosevkaFonts: "{{ lookup('file', '../files/iosevka/normal.json') | from_json }}"
    iosevkaAileFonts: "{{ lookup('file', '../files/iosevka/aile.json') | from_json }}"
    combinedFonts:
  include_role:
    name: "fonts"
    fontFilename: "{{ item.key }}"
    fontFamily: "{{ item.value }}"
  loop: "{{ allTheIconsFonts | combine(iosevkaFonts) | combine(iosevkaAileFonts) }}"
