---
- name: Install Cargo packages
  hosts: windows
  vars:
    packages: "{{ lookup('file', '../files/cargo-packages.json') | from_json }}"
  tasks:
    - name: Install versioned packages
      community.general.cargo:
        name: "{{ item.package }}"
        version: "{{ item.version }}"
        features: "{{ item.features | default([]) }}"
        state: present
      loop: "{{ packages | rejectattr('windows', 'is', false) | selectattr('version', 'defined') }}"

    - name: Install packages
      ansible.windows.win_powershell:
        script: |
          cargo install {{ item.package }} --git {{ item.git }}{{ "--branch " + item.branch if item.branch else "" }}{{ "--features " + item.features.join(",") if item.features else "" }}
      loop: "{{ packages | rejectattr('windows', 'is', false) | rejectattr('version', 'defined') }}"

    - ansible.builtin.debug:
        msg: "wasm-pack must be installed manually on Windows due to the OpenSSL dependency."

- name: Install Cargo packages
  hosts: linux
  vars:
    packages: "{{ lookup('file', '../files/cargo-packages.json') | from_json }}"
  tasks:
    - name: Install versioned packages
      community.general.cargo:
        name: "{{ item.package }}"
        version: "{{ item.version }}"
        features: "{{ item.features | default([]) }}"
        state: present
      loop: "{{ packages | selectattr('version', 'defined') }}"

    - name: Install packages
      shell:
        script: |
          cargo install {{ item.package }} --git {{ item.git }}{{ "--branch " + item.branch if item.branch else "" }}{{ "--features " + item.features.join(",") if item.features else "" }}
      loop: "{{ packages | rejectattr('version', 'defined') }}"
