---
- name: Install Chocolatey apps
  hosts: windows
  vars:
    apps: "{{ lookup('file', '../files/chocolatey-packages').strip().split() }}"
  tasks:
    - win_chocolatey:
        name: "{{ item }}"
        state: latest
      loop: "{{ apps | flatten(levels=1) }}"
