---
- name: Install Node.JS via fnm
  hosts: windows
  vars:
    versions: "{{ lookup('file', '../files/fnm-versions').strip().split() }}"
  tasks:
    - ansible.windows.win_powershell:
        script: |
          fnm use --install-if-missing {{ item }}
        error_action: stop
      loop: "{{ versions | flatten(levels=1) }}"

- name: Install Node.JS via fnm
  hosts: linux
  vars:
    versions: "{{ lookup('file', '../files/fnm-versions').strip().split() }}"
  tasks:
    - shell:
        script: |
          fnm use --install-if-missing {{ item }}
      loop: "{{ versions | flatten(levels=1) }}"
