---
- name: Install npm packages
  hosts: all
  vars:
    packages: "{{ lookup('file', 'npm-packages').strip().split() }}"
  tasks:
    - npm:
        name: "{{ parts[0] }}"
        version: "{{ parts[1] }}"
        state: present
        global: yes
      vars:
        parts: "{{ item | split('@') }}"
      loop: "{{ packages | flatten(level=1) }}"
