---
- name: Install Scoop applications
  hosts: windows
  vars:
    apps: "{{ lookup('file', 'scoop-packages').strip().split() }}"
  tasks:
    - name: Add buckets
      community.windows.win_scoop_bucket:
        name: "{{ item }}"
        state: present
      loop:
        - extras
        - nerd-fonts
        - java
        - misc
        - nonportable

    - name: Add custom buckets
      community.windows.win_scoop_bucket:
        name: "{{ item.name }}"
        repo: "{{ item.repo }}"
        state: present
      loop:
        - name: "smallstep"
          repo: "https://github.com/smallstep/scoop-bucket.git"

    - name: Install aria2 for faster downloads
      community.windows.win_scoop_bucket:
        name: "aria2"
        state: present

    - name: Disable aria2 warning
      ansible.windows.win_powershell:
        script: |-
          scoop config aria2-warning-enabled false

    - name: Install applications
      community.windows.win_scoop:
        name: "{{ item }}"
        state: present
      loop: "{{ apps | flatten(levels=1) }}"

    - name: Remove leftovers
      community.windows.win_scoop:
        name: "{{ item }}"
        state: absent
      loop:
        - vcredist2019
